
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: dtedatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
  myapp:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
      - wiremock
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dtedatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      APP_API_CEP_URL: http://wiremock:8080
      SERVER_PORT: 8081

volumes:
  db_data: